name: CD

on:
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: ubuntu-latest
    needs: [CI]
    environment:
      name: pypi
      url: https://pypi.org/p/gitv
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1
