name: CD

on:
  push:
    tags: ['v*']

jobs:
  build:
    uses: ./.github/workflows/main.yml
    permissions:
      contents: read
      packages: write
  release:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: pypi
      url: https://pypi.org/p/gitv
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1
